# Generated by Django 6.0.3 on 2026-03-16 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='Depth in the classification hierarchy (0 = root).')),
                ('sign', models.SmallIntegerField(default=1, help_text='1 for credit-normal (revenue), -1 for debit-normal (expense).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.accountclassification')),
            ],
            options={
                'verbose_name': 'Account Classification',
                'verbose_name_plural': 'Account Classifications',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.accountclassification')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DEACTIVATED', 'Deactivated'), ('REACTIVATED', 'Reactivated')], max_length=20)),
                ('changes', models.JSONField(default=dict, help_text='Snapshot of changed fields: {field: {old, new}}.')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='accounts.account')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Edit History',
                'verbose_name_plural': 'Account Edit Histories',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjustment',
                'verbose_name_plural': 'Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = credit, Negative = debit.', max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_details', to='accounts.account')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts.adjustment')),
            ],
            options={
                'verbose_name': 'Adjustment Detail',
                'verbose_name_plural': 'Adjustment Details',
            },
        ),
        migrations.CreateModel(
            name='AdjustmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('MODIFIED', 'Modified'), ('REVERSED', 'Reversed'), ('APPROVED', 'Approved')], max_length=20)),
                ('changes', models.JSONField(default=dict, help_text='Snapshot of changed fields: {field: {old, new}}.')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.adjustment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjustment History',
                'verbose_name_plural': 'Adjustment Histories',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.AddField(
            model_name='adjustment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='accounts.period'),
        ),
        migrations.CreateModel(
            name='SAPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Original payload from SAP for audit purposes.')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_records', to='accounts.account')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_records', to='accounts.period')),
            ],
            options={
                'verbose_name': 'SAP Record',
                'verbose_name_plural': 'SAP Records',
                'ordering': ['-period__year', '-period__month', 'account__code'],
                'unique_together': {('account', 'period')},
            },
        ),
    ]
