# Generated by Django 6.0.3 on 2026-03-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sociedad',
            field=models.CharField(choices=[('1000', 'Sociedad 1000'), ('1100', 'Sociedad 1100')], default='1100', help_text='Company code (sociedad) this account belongs to.', max_length=4),
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='sociedad',
            field=models.CharField(choices=[('1000', 'Sociedad 1000'), ('1100', 'Sociedad 1100')], default='1100', help_text='Company code (sociedad) this classification belongs to.', max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accountclassification',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('code', 'sociedad')},
        ),
        migrations.AlterUniqueTogether(
            name='accountclassification',
            unique_together={('code', 'sociedad')},
        ),
    ]
