# Generated by Django 6.0.3 on 2026-03-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_sociedad_accountclassification_sociedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountclassification',
            name='cat',
            field=models.CharField(blank=True, default='', help_text='PUC category identifier from the company schema.', max_length=255),
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='subcat',
            field=models.CharField(blank=True, default='', help_text='PUC subcategory identifier from the company schema.', max_length=255),
        ),
    ]
